site_name: Porfolio
site_author: Robert Bąk
site_description: >-
    Portfolio moich projektów z Data Science i AI!

repo_name: robetr286/portfolio
repo_url: https://github.com/robetr286/portfolio

theme:
  name: material
  palette:
    primary: lime

nav:
- Strona Domowa: index.md
- Obecny projekt:
  - "Talk_electronic": Talk_electronics/index.md
- Poprzednie projekty:
  - "Titanic": titanic/index.md
  - "Iris": iris/index.md
  